jedisct1/libhydrogen

impl/random.h
This code uses the random number generator present on ESP32 and ESP8266 based systems.
More information on esp32 random numbers can be found here https://techtutorialsx.com/2017/12/22/esp32-arduino-random-number-generation/ and the links contained in the blog post. For best results the radio interfaces (WiFi or Bluetooth) should be activated prior to calling the esp_random() function.
I'm using this code on heltec wifi lora 32 boards with platformio as build environment and it works just fine.
=> added support for esp-based system to hydo_random_init()

Makefile.arduino
Using the LibHydrogen zip produced by this makefile for Arduino Nano failed because impl/gimli-core/portable.h wasn't packaged in the zip.
=> Fix Arduino build

impl/random.h
Abstract the entropy collection through mbedTLS as there is no standard source for random and mbedTLS is included in the default distribution.
=> Add support for mbedOS platforms

impl/kx.h
hydro_kx_kk2: scalarmult(static_sk, peer_eph_pk)
scalarmult(static_sk, peer_static_pk)
scalarmult(eph_sk, peer_eph_pk)
scalarmult(eph_sk, peer_static_pk) instead of scalarmult(static_sk, peer_eph_sk) again
hydro_kx_kk3: scalarmult(eph_sk, peer_eph_pk)
scalarmult(static_sk, peer_eph_pk) instead of scalarmult(eph_sk, peer_static_pk) again from kk1
=> kx: kk2 and 3 pk check

impl/common.h, impl/x25519.h, tests/tests.c
- Remove a couple of unnecessary `../`s from `#include`s.
- Make some implicit type conversions in x25519.h into explicit ones, to clear some "potential loss of data" warnings.
=> Clear a few MSVC warnings

tests/tests.c
By default, when an `assert` fails in a debug binary on Windows, the system pops up a GUI dialog box asking whether it should Abort/Retry/Ignore in response to the failure, pausing program execution until one of these options is manually selected. Not good for automatic test runs!
=> Disable system dialog when tests fail on Windows

.gitignore, CMakeLists.txt, hydrogen-config.cmake.in
This adds support for building libhydrogen with CMake and&mdash;more importantly&mdash;easily integrating libhydrogen with CMake-based projects and IDEs.
The `CMakeLists.txt` file supports everything the `Makefile` does, including installation and automatically running tests on build. It also supports MSVC, as well as CMake's `find_package()` dependency mechanism, so a project using libhydrogen can add the following to its own `CMakeLists.txt` to pull in libhydrogen:
```cmake
#add_subdirectory(./libhydrogen)
find_package(hydrogen REQUIRED)
target_link_libraries(foo PRIVATE hydrogen::hydrogen)
```
=> Add CMake build system support

cmake/wasm32-wasi-toolchain.cmake
Works like the Arduino toolchain. To use, pass `-DCMAKE_TOOLCHAIN_FILE=cmake/wasm32-wasi-toolchain.cmake` in your CMake command line. You'll also need to specify a sysroot directory with `-DHYDROGEN_WASM32_WASI_SYSROOT_DIR=XXX`.
=> Add wasm32-wasi CMake cross-compile toolchain

.cmake-format.json, CMakeLists.txt, cmake/arduino-avr-toolchain.cmake
- Add a cmake_format configuration file and re-format with [`cmake_format 0.5.3`](https://pypi.org/project/cmake-format/).
- Shift the setting that controls `HYDRO_TARGET_DEVICE_XXX` definitions to the main `CMakeLists.txt`, so it can be configured by projects importing `libhydrogen` via `add_subdirectory`. The Arduino toolchain still automatically initializes this setting based on the target MCU.
- Prefix Arduino CMake toolchain options with `HYDROGEN_*`.
=> Fix up CMake formatting

CMakeLists.txt
When I was trying to add `libhydrogen` into `vcpkg`(https://github.com/microsoft/vcpkg/pull/7436), the `vcpkg`'s CI system reports it fails on Linux and macOS: 
https://dev.azure.com/vcpkg/public/_build/results?buildId=8415
https://dev.azure.com/vcpkg/public/_build/results?buildId=8418
I downloaded the port failure logs and got this:
>[1/6] /usr/bin/cc  -I/home/vcpkg/myagent/_work/4/s/buildtrees/libhydrogen/src/a1d93becec-95c16f0d25 -fPIC -g   -Os -march=native -fno-exceptions -Wall -Wextra -Wmissing-prototypes -Wdiv-by-zero -Wbad-function-cast -Wcast-align -Wcast-qual -Wfloat-equal -Wmissing-declarations -Wnested-externs -Wno-unknown-pragmas -Wpointer-arith -Wredundant-decls -Wstrict-prototypes -Wswitch-enum -Wno-type-limits -MD -MT CMakeFiles/hydrogen-tests.dir/tests/tests.c.o -MF …
=> Fix cmake not found error

CMakeLists.txt
Thanks @spinda for your advice in #72 .
This patch slso specifies VERBATIM for add_custom_command and add_custom_target as recommanded in https://stackoverflow.com/questions/35847655/when-should-i-quote-variables .
=> Quote CMAKE_COMMAND and CMAKE_CTEST_COMMAND

CMakeLists.txt
Needed to remove the function to prepend project directory to all file paths, since it used TRANSFORM function which is available in cmake 3.12+ only. Luckily, this operation was redundant since cmake computes relative paths from PROJECT_SOURCE_DIR anyway.
=> updated CMakeLists to enable configuration with cmake 3.1+

impl/random.h, impl/random/riot.h
Add support for [RIOT-OS](https://github.com/RIOT-OS/RIOT) to libhydrogen so we can just use the upstream version in the [RIOT `pkg`](https://github.com/RIOT-OS/RIOT/tree/master/pkg/libhydrogen).
=> random: add support for RIOT

impl/random.h, impl/random/rtthread.h
Hi,
It seems like you prefer to keep `SConscript` outside of the main repo. I understand that this could cause some inconveniences for you. Thus, this PR only contains minimum ports for RT-Thread.
As for the package `libhydrogen` in RT-Thread package center, currently it points to my fork, such that I can continue add examples for `libhydrogen` on RT-Thread without effecting the upstream repo.
https://github.com/wuhanstudio/libhydrogen
Hope this works.
=> Add RT-Thread Support

impl/x25519.h
The way `sub` is used in STROBE and libhydrogen does not encounter this
case because `sub` is always used on results which have been fully
`propagate`d, but if the field arithmetic code were copied and used in
another context, this bug may surface.
This was fixed in STROBE here:
https://sourceforge.net/p/strobe/code/ci/7d7f605380f573d06484accb61d08c5f4674b35a/
=> Fix the `sub` function so it computes the correct result even if the inputs are not the result of a `propagate`.

impl/common.h
Hi,
Tiny C Compiler defines `__GNUC__` but doesn't support `__thread`.
=> trivial fix for tcc

hydrogen.h, impl/common.h, impl/random.h, impl/random/linux_kernel.h
This adds basic support for building/using hydrogen in a Linux kernel (module) tree.
Right now, only one instance at a time is supported (or they'd clash on the random number pool, breaking security). To remedy this, I think the individual functions in `impl/random.h` except for `hydro_random_buf_deterministic` can be rewritten to use the kernel APIs (only when building in a Linux kernel or module tree) instead of Gimli. Alternatively, Linux kernel specific spinlocks can be introduced into those functions, but that's worse scalability. Either way, `hydro_random_buf_deterministic` can stay as-is, because it does not use the shared global state.
For our current usage, one instance at a time was sufficient (can be guaranteed with locking in the calling code), so I did not bother improving …
=> Add Linux kernel/module support

impl/random.h, impl/random/ch32.h
Currently, only CH32V30x series have hardware random number generator.
http://www.wch-ic.com/products/CH32V307.html
=> Add random support for CH32 MCUs

impl/random.h, impl/random/zephyr.h
We've tried to use `libhydrogen` in our project which is based on the nRF Connect SDK. And found out that `libhydrogen` incorrectly assumed the old nRF SDK.
Here is an adaptation for any Zephyr-based platform.
=> Added Zephyr integration

.github/workflows/codeql-analysis.yml, meson.build
Hi, Frank!
This branch adds a `meson.build` file for building libhydrogen. Not sure if you want another build system in your tree, but since I saw you have a few Makefiles and CMake already, I thought I would check :-)
If you aren't familiar with meson and its [wrap dependency system ](https://mesonbuild.com/Wrap-dependency-system-manual.html), this makes it easy for a meson project to take a dependency on another one, especially and even if the dependency is not available from the OS.
E.g., I want to depend on libhydrogen from a project that I'm working on that uses meson, but libhydrogen is not available from my OS's packages repository, so I added these commits to my project:
https://github.com/edmonds/vacon/commit/045c9202d13b9db2736f2770530d117390791441 …
=> Meson build system

hydrogen.h
This commit wraps the GCC pragma to ignore -Wdeclaration-after-statement diagnostics in an `#ifndef __cplusplus` guard since this pragma isn't needed when compiling in C++ mode.
Without this change, I get the following diagnostic from g++ when compiling a C++ project that includes hydrogen.h:
../subprojects/libhydrogen/hydrogen.h:11:32: warning: option ‘-Wdeclaration-after-statement’ is valid for C/ObjC but not for C++ [-Wpragmas]
11 | #pragma GCC diagnostic ignored "-Wdeclaration-after-statement"
|                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
=> hydrogen.h: Add `#ifndef __cplusplus` guard for pragma not valid in C++

impl/common.h, impl/random.h, impl/random/cheriot.h
This PR adds support for [CHERIoT](https://cheriot.org/), an RTOS designed to provide hardware based memory safety on embedded systems using [Capability Hardware Enhanced RISC Instructions](https://en.wikipedia.org/wiki/Capability_Hardware_Enhanced_RISC_Instructions)
It was developed by [Configured Things](https://www.configuredthings.com/) with funding from the [Digital Security by Design](https://www.dsbd.tech) program.
=> Add CHERIoT support
